spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storemanager
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update